# Generated by Django 3.2.5 on 2021-08-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appp_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(choices=[('F', 'Furnished'), ('N', 'Non-Furnished')], max_length=1)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('rent', models.IntegerField()),
                ('agreement', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('floor', models.CharField(max_length=20)),
                ('negotiable', models.BooleanField()),
                ('rented', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=10)),
                ('nid_file', models.FileField(blank=True, null=True, upload_to='nids/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abash.property')),
                ('flat', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('ward', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bedroom_no', models.IntegerField()),
                ('bathroom_no', models.IntegerField()),
                ('drawing_no', models.IntegerField(null=True)),
                ('dining_no', models.IntegerField(null=True)),
                ('balcony_no', models.IntegerField(null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abash.property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(blank=True, null=True, upload_to='more_property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abash.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abash.user_details'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.user_details')),
            ],
        ),
    ]
