# Generated by Django 3.2.5 on 2021-09-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.user_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Appp_rating',
        ),
    ]
