# Generated by Django 3.2.5 on 2021-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0003_auto_20210929_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='area_sqft',
        ),
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='agreement',
            field=models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily'), ('A', 'Any')], max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('FF', 'Family Flat'), ('BF', 'Bachelor Flat'), ('FS', 'Family Sublet'), ('BS', 'Bachelor Sublet'), ('AN', 'Any')], max_length=2, null=True),
        ),
    ]
