# Generated by Django 3.2.5 on 2021-10-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0006_rename_city_location_upazila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('deleted', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.user_details')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.property')),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('deleted', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abash.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abash.user_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='received_booking',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abash.requested_booking'),
        ),
    ]
