# Generated by Django 3.2.5 on 2021-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0007_auto_20211006_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received_booking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='received_booking',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requested_booking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requested_booking',
            name='start_date',
            field=models.DateField(),
        ),
    ]
