# Generated by Django 3.2.5 on 2021-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0008_auto_20211006_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received_booking',
            name='deleted',
            field=models.BooleanField(null=True),
        ),
    ]
