# Generated by Django 3.2.5 on 2021-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abash', '0009_alter_received_booking_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_booking',
            name='deleted',
            field=models.BooleanField(null=True),
        ),
    ]
